# We cannot use latest ROS distributions in travis since we are limited to trusty
# So, let's use docker.
sudo: required
dist: trusty
language: c++
notifications:
env:
  matrix:
    - CI_ROS_DISTRO=kinetic
    - CI_ROS_DISTRO=melodic
before_script:
  - case $CI_ROS_DISTRO in "kinetic") export DISTRO=xenial;; "melodic") export DISTRO=bionic;; esac;
  - export DOCKER_IMAGE=ubuntu:$DISTRO
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - if [ ! "$ROS_PARALLEL_JOBS" ]; then export ROS_PARALLEL_JOBS="-j8 -l8";  fi
  - docker images
script:
  - docker run -v $HOME:$HOME -e CI_SOURCE_PATH -e REPOSITORY_NAME -e HOME -e DISTRO -e CI_ROS_DISTRO -e ROS_PARALLEL_JOBS $DOCKER_IMAGE bash -c 'cd $CI_SOURCE_PATH; source .travis.sh'
